import type {
  AbiMethod,
  BindingGenerationOptions,
  ContractAbi,
  WasmExportEntry,
  WasmExportKind,
} from "./contract-types.js";

function toUint8Array(bytes: BufferSource): Uint8Array {
  if (bytes instanceof Uint8Array) return bytes;
  if (bytes instanceof ArrayBuffer) return new Uint8Array(bytes);
  return new Uint8Array(bytes.buffer, bytes.byteOffset, bytes.byteLength);
}

function inferMode(name: string): AbiMethod["mode"] {
  const lower = name.toLowerCase();
  if (
    lower.startsWith("query_") ||
    lower.startsWith("get_") ||
    lower.startsWith("read_") ||
    lower.startsWith("view_")
  ) {
    return "query";
  }
  return "call";
}

export function extractWasmExports(bytes: BufferSource): WasmExportEntry[] {
  // Copy to a plain ArrayBuffer-backed view for strict TS compatibility.
  const mod = new WebAssembly.Module(Uint8Array.from(toUint8Array(bytes)));
  return WebAssembly.Module.exports(mod).map((entry) => ({
    name: entry.name,
    kind: entry.kind as WasmExportKind,
  }));
}

export function abiFromWasmExports(bytes: BufferSource): ContractAbi {
  const methods: AbiMethod[] = extractWasmExports(bytes)
    .filter((entry) => entry.kind === "function")
    .map((entry) => ({ name: entry.name, mode: inferMode(entry.name) }));
  return { methods };
}

export function generateTypeScriptBindings(
  abi: ContractAbi,
  options: BindingGenerationOptions,
): string {
  const clientVar = options.clientVarName ?? "client";
  const lines: string[] = [];
  lines.push("// Auto-generated by @sierpinskichain/sdk/contract");
  lines.push("import type { ContractClient } from \"@sierpinskichain/sdk/contract\";");
  lines.push("");
  lines.push(`export function create${options.contract}Bindings(${clientVar}: ContractClient) {`);
  lines.push("  return {");
  for (const method of abi.methods) {
    if (method.mode === "query") {
      lines.push(
        `    async ${method.name}(key: string) { return ${clientVar}.query({ contract: "${options.contract}", key }); },`,
      );
    } else {
      lines.push(
        `    async ${method.name}(key: string, value: string) { return ${clientVar}.call({ contract: "${options.contract}", key, value }); },`,
      );
    }
  }
  lines.push("  };");
  lines.push("}");
  return lines.join("\n");
}
